# Generated by Django 4.1.5 on 2023-03-22 02:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic', '0006_alter_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='target_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
