# Generated by Django 4.1.5 on 2023-03-22 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic', '0007_topic_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='target_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
