# Generated by Django 4.1.5 on 2023-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_category', '0010_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
    ]
