# Generated by Django 4.1.5 on 2023-03-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_topic_private', '0004_auto_20230301_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicprivate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
