# Generated by Django 3.1.7 on 2022-11-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment', '0004_auto_20160315_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
            ],
            options={
                'verbose_name': 'commentTag',
                'verbose_name_plural': 'commentTags',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spirit_comment.commenttag'),
        ),
    ]
