# Generated by Django 3.1.7 on 2022-11-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment', '0005_auto_20221113_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttag',
            name='name',
            field=models.CharField(max_length=124, unique=True),
        ),
    ]
