# Generated by Django 3.1.7 on 2022-11-21 08:53

from django.db import migrations, models
import spirit.comment.models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment', '0006_auto_20221114_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttag',
            name='model_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=spirit.comment.models.get_model_file_uploader_path),
        ),
    ]
