# Generated by Django 3.1.7 on 2022-11-23 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment', '0008_auto_20221121_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttag',
            name='report_file',
        ),
        migrations.AddField(
            model_name='comment',
            name='custom_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
