# Generated by Django 3.1.7 on 2022-11-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_comment', '0009_auto_20221123_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='custom_date',
            field=models.DateTimeField(),
        ),
    ]
