# Generated by Django 4.1.5 on 2023-03-22 02:11

from django.db import migrations
import spirit.core.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0016_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=spirit.core.utils.models.AutoSlugField(allow_unicode=True, blank=True, db_index=False, populate_from='user.email'),
        ),
    ]
